from typing import Annotated
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langgraph.graph import MessagesState

class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length

class RiskDebateState(TypedDict):
    risky_response: Annotated[str, "Response by the risky analyst"]
    safe_response: Annotated[str, "Response by the safe analyst"]
    neutral_response: Annotated[str, "Response by the neutral analyst"]


#MessagesState automatically includes a messages: Annotated[List[Message], "Chat history"]' field
class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    symbol: Annotated[str, "Ticker symbol for trade"]
    trade_signal: Annotated[dict, "Final trade signal structure with nested data"]
    trade_signal_args: Annotated[dict, "Parsed numeric args used for execution"]
    final_report: Annotated[str, "Final complete report summary for output to user"]