version: "3.9"

networks:
  stock-network:
    external: true
    name: kafka_stock-network

services: 
  sentiment-agent:
    build: .
    command: python main_sentiment.py
    networks:
      - stock-network
    env_file:
      - .env
    environment:
      KAFKA_BROKER: kafka:29092
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    restart: unless-stopped

  market-agent:
    build: .
    command: python agents/main_market.py      # 👈 run only this file
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/app
      - ./reports:/app/reports
    restart: unless-stopped
