networks:
  stock-network:
    external: true
    name: kafka_stock-network

services:
  market-producer:
    build: .
    command: ["python", "producers/market_data_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    restart: unless-stopped

  news-producer:
    build: .
    command: ["python", "producers/news_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    restart: unless-stopped

  sentiment-producer:
    build: .
    command: ["python", "producers/sentiment_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    restart: unless-stopped

  fundamental-producer:
    build: .
    command: ["python", "producers/fundamental_data_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    restart: unless-stopped

  fundamental-report-producer:
    build: .
    command: ["python", "producers/fundamental_report.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
      KNOWLEDGE_BASE_DIR: /knowledge_base
    env_file:
      - .env
    volumes:
      - ../knowledge_base:/knowledge_base
    restart: unless-stopped