networks:
  stock-network:
    external: true
    name: kafka_stock-network

services:
  market-producer:
    build: .
    command: ["python", "producers/market_data_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    restart: unless-stopped

  news-producer:
    build: .
    command: ["python", "producers/news_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    restart: unless-stopped

  sentiment-producer:
    build: .
    command: ["python", "producers/sentiment_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
      WEBHOOK_URL: http://twitter-webhook:5001
    env_file:
      - .env
    volumes:
      - ./sentiment_logs:/app/sentiment_logs
    restart: unless-stopped

  fundamental-producer:
    build: .
    command: ["python", "producers/fundamental_data_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    restart: unless-stopped

  fundamental-report-producer:
    build: .
    command: ["python", "producers/fundamental_report.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
      KNOWLEDGE_BASE_DIR: /knowledge_base
    env_file:
      - .env
    volumes:
      - ../knowledge_base:/knowledge_base
    restart: unless-stopped

  candle-producer:
    build: .
    command: ["python", "producers/candle_producer.py"]
    networks:
      - stock-network
    environment:
      KAFKA_BROKER: kafka:29092
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  twitter-webhook:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "webhook_receiver.py"]
    networks:
      - stock-network
    environment:
      WEBHOOK_RECEIVER_PORT: 5001
    ports:
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - .:/app


  ##########################################
  # ADD THIS: Cloudflare Tunnel
  ##########################################
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - twitter-webhook
    networks:
      - stock-network
    restart: unless-stopped

