networks:
  stock-network:
    external: true
    name: kafka_stock-network

services:
  fastapi-app:
    build: .
    container_name: websocket-fastapi
    networks:
      - stock-network
    ports:
      - "8001:8001"
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=pathway-redis
      - REDIS_PORT=6379
    volumes:
      - .:/code
    working_dir: /code
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped